### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by jkshenton** [CCP-NC/ccpnc-database#8]
In GitLab by @AKM2022on Sep 27, 2018, 11:29

I Just tried this database and found some issues. The search pattern of chemical name is case sensitive, for example it's not displaying anything if I type 'alanine' I had to type Alanine. I think it would be really nice if you could display the chemical structure along with the chemical formula.
Is it possible to show the name of the compound or CCDC refcode for the downloaded file? at the moment the file name is just 'doc' for all  the compounds.
There is no option to edit the chemical name after uploading, at least the owner of the file should have the permission to edit all the details right?

Thank you very much.

**Comment by Sathya-S3** [comment]
@jkshenton I believe this issue can be resolved (point 3 is uncertain, maybe needs discussing with the working group).
1. Case sensitivity of chemical names has been resolved. The same 'alanine' and 'Alanine' example can be tested on the database to return the same results.
2. The downloaded filename is meaningful in the latest version with MRD number followed by version number. The same naming convention is also used for metadata files in json and csv formats.
3. Simone has already clarified that the chemical name can't be changed after upload. It's not clear if there were follow-up discussions on the topic.
