### ISSUE TITLE
Change the wording

### ISSUE THREAD

**Issue by jkshenton** [CCP-NC/ccpnc-database#9]
In GitLab by @stur86 on May 20, 2019, 11:31

Reword “The files will be added as separate entries to the database, so please use this just to upload in group lots of different structures, not lots of versions of the same structure.”

(e.g. “Files will be added as separate entries to the database and is intended for use when adding a group of multiple different structures in a single upload. This feature is not for adding multiple of versions of the same structure.”)

**Comment by Sathya-S3** [comment]
This issue has been addressed in the commit [8d8fddf](https://github.com/CCP-NC/ccpnc-database/commit/8d8fddf6256cd3e81a5bd284ae524df9192f93ff). Closing this issue.
